### ISSUE TITLE
Build Failed: annot use threeWayMergeInput

### ISSUE THREAD

**Issue by Congee** [carthewd/c3#2]
Hi there, thank you for this tool. I came across this error while trying to build it. I am using fd8689f16dc3f71cabb125df9400a1b1f3d904a8
```
pkg/codecommit/pr_merge.go:58:16: cannot use threeWayMergeInput (type *codecommit.MergePullRequestBySquashInput) as type *codecommit.MergePullRequestByThreeWayInput in argument to mergeThreeWay
```

**Comment by carthewd** [comment]
This functionality is still being worked on and this crept in... big thanks to @pwdebruin1 for the fix!
